### ISSUE TITLE
Missing file?

### ISSUE THREAD

**Issue by pmsuite** [ibm-wch/wch-site-application#6]
I am attempting to run Oslo locally. However, I seem to be missing a file. It is the ajax-loader.gif. The key error is below and the ful set of errors below that. If I run the Oslo site locally, I see the footer and search bar and nothing else.

'/Users/dkcmac/wch-site-application-master/src/app/components/generic/carousel/ajax-loader.gif

WARNING in ./src/app/components/generic/carousel/carousel.component.scss
(Emitted value instead of an instance of Error) postcss-url: /Users/dkcmac/wch-site-application-master/src/app/components/generic/carousel/carousel.component.scss:20:3: Can't read file '/Users/dkcmac/wch-site-application-master/src/app/components/generic/carousel/ajax-loader.gif', ignoring
NonErrorEmittedError: (Emitted value instead of an instance of Error) postcss-url: /Users/dkcmac/wch-site-application-master/src/app/components/generic/carousel/carousel.component.scss:20:3: Can't read file '/Users/dkcmac/wch-site-application-master/src/app/components/generic/carousel/ajax-loader.gif', ignoring
    at Object.emitWarning (/Users/dkcmac/wch-site-application-master/node_modules/webpack/lib/NormalModule.js:117:16)
    at result.warnings.forEach (/Users/dkcmac/wch-site-application-master/node_modules/postcss-loader/lib/index.js:148:49)
    at Array.forEach (<anonymous>)
    at postcss.process.then (/Users/dkcmac/wch-site-application-master/node_modules/postcss-loader/lib/index.js:148:27)
    at <anonymous>
 @ ./src/app/components/generic/carousel/carousel.component.ts 88:21-57
 @ ./src/app/components/generic/generic.layout.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by ThomasHurek** [comment]
Hello pmsuite,
the issue is likely not the missing gif but one of the following:
- did you configure your tenant in /src/app/Constants.ts ?
- did you configure either * or localhost in Security settings of your content hub?

**Comment by pmsuite** [comment]
I realized I forgot to remove the '//' to comment out the two lines in the Constant.ts.It now works. Thank you for the answer.

I still get the Warning about the missing file. The file does not exist but, I have not seen it effect the Oslo site yet.
